FROM python:latest
WORKDIR /app
COPY futbol_app /app
COPY reservas /app
COPY requirements.txt /app
COPY manage.py /app
RUN pip install -r requirements.txt
#RUN python manage.py makemigrations
RUN python manage.py migrate
RUN python manage.py migrate --fake reservas
RUN python manage.py migrate --fake auth_user
EXPOSE 8000
CMD ["python", "manage.py", "runserver"]